# Generated by Django 4.2.16 on 2025-11-27 11:23

import core.models.recipe
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe.recipe_image_file_path),
        ),
    ]
